services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: ominimo-blog-app-dev
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/vendor
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:5173"
    env_file:
      - .env
    environment:
      - DB_HOST=mariadb
      - REDIS_HOST=redis
      - MAIL_HOST=mailpit
      - NODE_ENV=development
    depends_on:
      - mariadb
      - mailpit
      - redis
    networks:
      - ominimo-blog-dev

  mariadb:
    image: mariadb:11.3
    container_name: ominimo-blog-mariadb-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data_dev:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - ominimo-blog-dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ominimo-blog-phpmyadmin-dev
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on:
      - mariadb
    networks:
      - ominimo-blog-dev

  mailpit:
    image: axllent/mailpit:latest
    container_name: ominimo-blog-mailpit-dev
    restart: unless-stopped
    ports:
      - "${MAIL_PORT:-1025}:1025"
      - "${MAILPIT_WEB_PORT:-8025}:8025"
    networks:
      - ominimo-blog-dev

  redis:
    image: redis:7-alpine
    container_name: ominimo-blog-redis-dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - ominimo-blog-dev

volumes:
  mariadb_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  ominimo-blog-dev:
    driver: bridge
